### ISSUE TITLE
Add SymReal Type

### ISSUE THREAD

**Issue by eldritch-cookie** [lsrcz/grisette#118]
looking at sbv it has support for both floats of arbitrary precision and rational numbers could grisette add support for them?

**Comment by lsrcz** [comment]
Hi @eldritch-cookie,

Yeah, I will be glad to add them. I still have plenty of stuff to do at this time, but I will put this into my todo list.

**Comment by lsrcz** [comment]
`SymAlgReal` has been added in #228, and `SymFP` has been added in #207.
